### ISSUE TITLE
Check reference format

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/FMFun2019#3]
From R1:

_Some itemizations in the submission are not clear. For example,
- what do [20], [21] and [22] mean on page 3 and 4. It is a wired way to present them if they mean the reference number.
- In Page 4, [22]^5, there is no footnote number 5 on this page._

**Comment by JamesHDavenport** [comment]
Already fixed footnote issue under a different issue; Added "From" to these.

**Comment by JamesHDavenport** [comment]
Fixed

**Comment by JamesHDavenport** [comment]
Note that we need a fixes document: I’ll start this, but you won’t see it until my laptop connects.
James (3G in train)

Sent from my iPhone

On 17 Nov 2019, at 16:02, James Davenport <masjhd@bath.ac.uk<mailto:masjhd@bath.ac.uk>> wrote:

Fixed
