### ISSUE TITLE
Check all footnotes

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/FMFun2019#6]
Do we need them all?

**Comment by JamesHDavenport** [comment]
I'd have thought we did. But curiously note 5 seems to have gone missing.

**Comment by JamesHDavenport** [comment]
Fixed this one (as text, not footnote)

**Comment by JamesHDavenport** [comment]
I think I'll declare this one closed now.

**Comment by JamesHDavenport** [comment]
Declared closed.
